### ISSUE TITLE
modularise tests.js?

### ISSUE THREAD

**Issue by jsms90** [njsfield/error-handling-workshop#1]
@njsfield Based on the feedback that FAC10 received during week 4 code review and s-g-c:
https://github.com/FAC10/week4-ammp/issues/65

and the way that some of them structured their files:
https://github.com/FAC10/week4-SoFLY/tree/master/tests

it might be nice to use this to show them a good example of modularising their test files too?

Since your functions are nicely modularised in the `modules` directory, it would be easy to just reuse that structure  i.e. Keep `tests.js` in root. Then have a `tests` folder, with each file named as:
+ `validateage.test.js`
+ `validateemail.test.js`
etc.
(Also nice to camel case these file names?)

Just an idea. But it would probably be good timing :smile:

**Comment by njsfield** [comment]
Good shout! Have amended
